# Site
name: "1oopro.com"
title: "아웃풋 트레이닝"
description: "개발 블로그입니다. 토이 프로젝트, 기술 서적 리뷰, 컨퍼런스 등 다양한 정보를 공유합니다."
logo: 'assets/images/logo.png'
favicon: 'assets/images/logo.png'
baseurl: ''
assetsurl: 'assets'
google_analytics: ''
disqus: '1oopro-com'
# mailchimp-list: 'https://wowthemes.us11.list-manage.com/subscribe/post?u=8aeb20a530e124561927d3bd8&amp;id=8c3d2d214b'
include: ["_pages"]
permalink: /:title/
keep_files: [assets]

# Authors
authors:
  1oopro:
    name: '1oopro'
    display_name: '백프로'
    avatar: 'assets/images/avatar.jpg'
    # gravatar: ''
    email: 'diveintotechnology@gmail.com'
    web: 'https://1oopro.com'
    twitter: 'https://twitter.com/iam1oopro'
    description: "This is the author box. Write a short description of the author here."

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'

# Pagination 
paginate: 6
paginate_path: /page:num/
    
# Other
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true

# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "disabled"
adsense-data-ad-client: "ca-pub-3412143450191416"
adsense-data-ad-slot: "1363087678"

facebook:
  app_id: '378931686293798'
  username: iam.seoyeongbaek
  comment: true

# Lazy Images ("enabled" or "disabled")
lazyimages: "disabled"

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]
