# Site
name: "baek.dev"
title: "아웃풋 트레이닝"
description: "개발 블로그입니다. 토이 프로젝트, 기술 서적 리뷰, 컨퍼런스 등 다양한 정보를 공유합니다."
logo: 'assets/images/logo.png'
favicon: 'assets/images/logo.png'
url : 'https://baek.dev'
baseurl: ''
assetsurl: 'assets'
google_analytics: 'UA-148617191-1'
disqus: '1oopro-com'
# mailchimp-list: 'https://wowthemes.us11.list-manage.com/subscribe/post?u=8aeb20a530e124561927d3bd8&amp;id=8c3d2d214b'
include: ["_pages"]
permalink: /post/:title/
keep_files: [assets]

# Authors
authors:
  1oopro:
    name: 'baek.dev'
    display_name: 'baek.dev'
    avatar: 'assets/images/profile9.png'
    email: 'diveintotechnology@gmail.com'
    web: 'https://baek.dev'
    twitter: 'https://twitter.com/baek.dev'
    github: 'https://github.com/divetech'
    description: "백엔드 개발자 & 아웃풋 트레이닝 중"

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'

# Pagination 
paginate: 6
paginate_path: /page:num/
    
# Other
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true

# Adsense (change to "enabled" to activate, also your client id.)
adsense: "enabled"
adsense-data-ad-client: "ca-pub-6059434733081357"

facebook:
  app_id: '378931686293798'
  username: iam.seoyeongbaek
  comment: true

# Lazy Images ("enabled" or "disabled")
lazyimages: "disabled"

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]
